#!/bin/sh

# Copyright (c) 2016 Open Baton (http://www.openbaton.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

OPENBATON_BASE_DIR=/usr
OPENBATON_PLUGINS_DIR=${OPENBATON_BASE_DIR}/lib/openbaton/plugins
OPENBATON_LOGS_DIR=/var/log/openbaton


####################
#### Open Baton ####
####################

clean_plugins () {
    export OPENBATON_PLUGINS_DIR="${OPENBATON_PLUGINS_DIR}"
    if [ -d ${OPENBATON_PLUGINS_DIR} ]; then
    	rm -r ${OPENBATON_PLUGINS_DIR}
        log_success_msg "Cleaning the environment: deleted plugins"
    fi
}

clean_logs () {
    export OPENBATON_LOGS_DIR="${OPENBATON_LOGS_DIR}"
    if [ -d ${OPENBATON_LOGS_DIR} ]; then
    	rm -r ${OPENBATON_LOGS_DIR}
        log_success_msg "Cleaning the environment: deleted logs"
    fi
}

# TODO: Add clean properties

clean () {
    clean_plugins
    clean_logs
}


##############
#### Main ####
##############

case "${1}" in
  purge)
    clean
  ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
  ;;

  *)
    log_failure_msg "postrm called with unknown argument ${1}"
    exit 1
  ;;

esac

exit 0

