#!/bin/sh

# Copyright (c) 2016 Open Baton (http://www.openbaton.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

OPENBATON_COMPONENT_NAME_FANCY="NFV Orchestrator (NFVO)"
OPENBATON_COMPONENT_NAME=nfvo
OPENBATON_COMPONENT_RELATIVE_SUBPATH=nfvo

OPENBATON_COMPONENT_JAR_FILE_NAME=openbaton-${OPENBATON_COMPONENT_NAME}
OPENBATON_COMPONENT_JAR_INSTALL_DIR=/usr/lib/openbaton/${OPENBATON_COMPONENT_RELATIVE_SUBPATH}


####################
#### Open Baton ####
####################

remove_existing_old_version_installed () {
    if [ -d ${OPENBATON_COMPONENT_JAR_INSTALL_DIR} ]; then
        openbaton_component_jar_file_name_versioned=$(ls -ct ${OPENBATON_COMPONENT_JAR_INSTALL_DIR} | grep "${OPENBATON_COMPONENT_JAR_FILE_NAME}" | grep "jar" | head -n 1)
        if [ "${openbaton_component_jar_file_name_versioned}" != "" ]; then
            rm ${OPENBATON_COMPONENT_JAR_INSTALL_DIR}/${openbaton_component_jar_file_name_versioned}
            log_success_msg "Removing old Open Baton ${OPENBATON_COMPONENT_NAME_FANCY} .."
        fi
    fi
}


##############
#### Main ####
##############

case "${1}" in  
    install|upgrade)
        remove_existing_old_version_installed
        ;;
    remove|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        log_failure_msg "preinst called with unknown argument ${1}"
        exit 1
        ;;
esac

exit 0
