#!/bin/sh -e

. /lib/lsb/init-functions

OPENBATON_BASE=/usr
OPENBATON_PLUGINS_FOLDER=${OPENBATON_BASE}/lib/openbaton/plugins
OPENBATON_LOGS_FOLDER=/var/log/openbaton

USER="$(id -un 2>/dev/null || true)"

checkBinary () {
    if command -v $1 >/dev/null 2>&1 ; then
        log_success_msg "Checking for '$1'" 
        return 0
    else
        log_failure_msg "Checking for '$1'"
        return 1
    fi
}

_ex='sh -c'
if [ "${USER}" != 'root' ]; then
    if checkBinary sudo; then
        _ex='sudo -E sh -c'
    elif checkBinary su; then
        _ex='su -c'
    fi
fi


####################
#### Open Baton ####
####################

stopNFVO () {
    instance=$(ps aux | grep -v grep | grep "openbaton-*jar" | wc -l)
    if [ ${instance} -ne 0 ]; then
        if $_ex 'systemctl stop openbaton-nfvo.service' >/dev/null ; then
    	    log_success_msg "Stopping the Open Baton NVFO .."
        elif $_ex 'stop openbaton-nfvo' >/dev/null ; then
    	    log_success_msg "Stopping the Open Baton NVFO .."
        else
            log_failure_msg "Stopping the Open Baton NFVO"
        fi
    fi
}

stopNFVO

