#!/bin/sh -e

. /lib/lsb/init-functions

OPENBATON_NFVO_CONFIG_FILE=/etc/openbaton/openbaton.properties
INSTALL_DIR=/usr/lib/openbaton
PID_FILE=/var/run/openbaton-nfvo.pid
DAEMON_USER=root
OSTYPE=$(uname)


###################
#### Rabbitmq #####
###################

check_rabbitmq () {
	if [ "$OSTYPE" = "Linux" ]; then
        instance=$(ps aux | grep -v grep | grep rabbitmq | grep server | wc -l) 
        if [ ${instance} -eq 0 ]; then
            log_warning_msg "rabbit is not running, let's try to start it"
			start_rabbitmq                        
        fi
    elif [ ${OSTYPE} -eq "Darwin" ]; then
        instance=$(ps aux | grep -v grep | grep rabbitmq | grep server | wc -l) 
        if [ ${instance} -eq 0 ]; then
            log_warning_msg "rabbitmq is not running, let's try to start it"
			start_rabbitmq                        
        fi
    fi    
}

start_rabbitmq () {
    $(rabbitmq-server -detached)
    if [ $? -ne 0 ]; then
        log_failure_msg "rabbitmq is not running properly (check the problem in /var/log/rabbitmq.log)"
        exit 1
    fi
}


####################
#### Open Baton ####
####################

get_pid() {
	local PID
	if [ -e "$PID_FILE" ]; then
		PID=$(cat "$PID_FILE")
	fi

	if [ -n "$PID" ]; then
		echo $PID
	else
		echo -1
	fi
}

check_already_running () {
    if [ "$OSTYPE" = "Linux" ]; then
        instance=$(ps aux | grep -v grep | grep "openbaton-nfvo" | grep jar | wc -l)
        if [ ${instance} -ne 0 ] ; then
            log_warning_msg "OpenBaton NFVO is already running"
            exit 1
        fi
    elif [ ${OSTYPE} -eq "Darwin" ]; then
        ID=$(get_pid)

	    if [ "$ID" == "-1" ]; then
		    echo "0"
	    elif [ -n "$(ps -p"$ID" -opid=)" ]; then
		    echo "1"
	    else
		    echo "0"
	    fi
    fi
}

set_jar_version () {
    # TODO: so far the most recent openbaton-nfvo jar is chosen to be executed
	#       -> add alternative version selection (with prompt question and/or with command line -v parameter)
	OPENBATON_NFVO_JAR=$(ls -ct ${INSTALL_DIR} | grep "openbaton" | grep jar | head -n 1)
	if [ ${OPENBATON_NFVO_JAR} = "" ]; then
        log_failure_msg "The Open Baton NFVO is not installed (jar-file not found)"
		exit 1
    fi
}

configure () {
    check_already_running
    check_rabbitmq
    if [ "$OSTYPE" = "Linux" ]; then
        set_jar_version
    fi
}

start () {
    configure
    log_success_msg "Starting the Open Baton NFVO .."
    if [ "$OSTYPE" = "Linux" ]; then
        start-stop-daemon --start --background --pidfile ${PID_FILE} --make-pidfile --user ${DAEMON_USER} --chuid ${DAEMON_USER} --exec /usr/bin/java -- -jar ${INSTALL_DIR}/${OPENBATON_NFVO_JAR} --spring.config.location=file:${OPENBATON_NFVO_CONFIG_FILE}
    elif [ ${OSTYPE} -eq "Darwin" ]; then
        nohup "$JAVACMD" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.openbaton.nfvo.main.Application --spring.config.location=file:${OPENBATON_NFVO_CONFIG_FILE} > /dev/null 2>&1 &
        OPENBATON_PID="-1"
		TRIES=10

		while [ "$DAEMON_RUNNING" == "0" -a $TRIES -gt 0 ]; do
			DAEMON_RUNNING=$(daemon_running)
			echo -n "."

			DAEMON_PID="$(daemon_get_pid)"
			TRIES=$(($TRIES-1))
			sleep 1
		done

		if [ $TRIES -eq 0 ]; then
			echo " Failed to start process. EXITING."
			echo "Failed command line: $ $DAEMON $DAEMON_CMD"
			exit 2
		fi

		echo " $DAEMON_NAME (pid $DAEMON_PID)."
    fi
}

stop () {
    log_success_msg "Stopping the Open Baton NFVO .."
    if [ "$OSTYPE" = "Linux" ]; then
        start-stop-daemon --stop --pidfile $PID_FILE
    elif [ ${OSTYPE} -eq "Darwin" ]; then
        launchctl stop "$LAUNCHD_APP_LABEL"
    fi
}

restart () {
    stop
    start
}



usage () {
    echo "Open Baton NFVO"
    if [ "$OSTYPE" = "Linux" ]; then
        echo "Usage:\n\t [openbaton-nfvo start|stop|restart] | [service openbaton-nfvo start|stop|restart] | [start|stop openbaton-nfvo] | [systemctl start|stop openbaton-nfvo.service]"
    elif [ ${OSTYPE} -eq "Darwin" ]; then
        echo "Usage:\n\t openbaton-nfvo [status|start|stop|restart]"
    fi
}

function status {
    if [ "$OSTYPE" = "Linux" ]; then
        #TODO status function for linux
        usage
    elif [ ${OSTYPE} -eq "Darwin" ]; then
        PROCESS_PID=$(launchctl list | grep "$LAUNCHD_APP_LABEL" | awk {'print $1}')
        if [ "$PROCESS_PID" != "-" ]; then
            echo "OpenBaton NFVO is running"
        else
            echo "OpenBaton NFVO is stopped"
        fi
    fi
}

##
#   MAIN
##

if [ ${#} -eq 0 ]
   then
        usage
        exit 1
fi

for cmd in ${@}
do
    case ${cmd} in
        "start" )
            start ;;
        "stop" )
            stop ;;
        "restart" )
            restart ;;
        "status" )
            status ;;
         *)   
	        usage;;
    esac
    if [ ${?} -ne 0 ];
    then
	    exit 1
    fi
done
