package org.openbaton.catalogue.mano.common.monitoring;

/**
 * Created by mob on 26.10.15.
 */
public enum FaultType {

    //Compute faults
    COMPUTE,
    COMPUTE_HOGS,
    COMPUTE_HOGS_CPU,
    COMPUTE_HOGS_MEMORY,
    COMPUTE_CRASH,
    COMPUTE_CODE_CORRUPTION,
    COMPUTE_DATA_CORRUPTION,

    //IO faults
    IO,

    IO_NETWORK_FRAME_RECEIVE,
    IO_NETWORK_FRAME_RECEIVE_CORRUPTION,
    IO_NETWORK_FRAME_RECEIVE_DROP,
    IO_NETWORK_FRAME_RECEIVE_DELAY,
    IO_NETWORK_FRAME_TRANSMIT,
    IO_NETWORK_FRAME_TRANSMIT_CORRUPTION,
    IO_NETWORK_FRAME_TRANSMIT_DROP,
    IO_NETWORK_FRAME_TRANSMIT_DELAY,

    IO_STORAGE_BLOCK_READS_CORRUPTION,
    IO_STORAGE_BLOCK_READS_DROP,
    IO_STORAGE_BLOCK_READS_DELAY,
    IO_STORAGE_BLOCK_WRITE_CORRUPTION,
    IO_STORAGE_BLOCK_WRITE_DROP,
    IO_STORAGE_BLOCK_WRITE_DELAY,

    //SERVICE FAULT
    VNF_NOT_AVAILABLE
}
